/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { JobPostService } from "../jobPost.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { JobPostCreateInput } from "./JobPostCreateInput";
import { JobPost } from "./JobPost";
import { JobPostFindManyArgs } from "./JobPostFindManyArgs";
import { JobPostWhereUniqueInput } from "./JobPostWhereUniqueInput";
import { JobPostUpdateInput } from "./JobPostUpdateInput";
import { ApplicationFindManyArgs } from "../../application/base/ApplicationFindManyArgs";
import { Application } from "../../application/base/Application";
import { ApplicationWhereUniqueInput } from "../../application/base/ApplicationWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class JobPostControllerBase {
  constructor(
    protected readonly service: JobPostService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: JobPost })
  @nestAccessControl.UseRoles({
    resource: "JobPost",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createJobPost(
    @common.Body() data: JobPostCreateInput
  ): Promise<JobPost> {
    return await this.service.createJobPost({
      data: {
        ...data,

        employer: data.employer
          ? {
              connect: data.employer,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,

        employer: {
          select: {
            id: true,
          },
        },

        id: true,
        location: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [JobPost] })
  @ApiNestedQuery(JobPostFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "JobPost",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async jobPosts(@common.Req() request: Request): Promise<JobPost[]> {
    const args = plainToClass(JobPostFindManyArgs, request.query);
    return this.service.jobPosts({
      ...args,
      select: {
        createdAt: true,
        description: true,

        employer: {
          select: {
            id: true,
          },
        },

        id: true,
        location: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: JobPost })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JobPost",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async jobPost(
    @common.Param() params: JobPostWhereUniqueInput
  ): Promise<JobPost | null> {
    const result = await this.service.jobPost({
      where: params,
      select: {
        createdAt: true,
        description: true,

        employer: {
          select: {
            id: true,
          },
        },

        id: true,
        location: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: JobPost })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JobPost",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateJobPost(
    @common.Param() params: JobPostWhereUniqueInput,
    @common.Body() data: JobPostUpdateInput
  ): Promise<JobPost | null> {
    try {
      return await this.service.updateJobPost({
        where: params,
        data: {
          ...data,

          employer: data.employer
            ? {
                connect: data.employer,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,

          employer: {
            select: {
              id: true,
            },
          },

          id: true,
          location: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: JobPost })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JobPost",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteJobPost(
    @common.Param() params: JobPostWhereUniqueInput
  ): Promise<JobPost | null> {
    try {
      return await this.service.deleteJobPost({
        where: params,
        select: {
          createdAt: true,
          description: true,

          employer: {
            select: {
              id: true,
            },
          },

          id: true,
          location: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/applications")
  @ApiNestedQuery(ApplicationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Application",
    action: "read",
    possession: "any",
  })
  async findApplications(
    @common.Req() request: Request,
    @common.Param() params: JobPostWhereUniqueInput
  ): Promise<Application[]> {
    const query = plainToClass(ApplicationFindManyArgs, request.query);
    const results = await this.service.findApplications(params.id, {
      ...query,
      select: {
        applicant: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        jobPost: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/applications")
  @nestAccessControl.UseRoles({
    resource: "JobPost",
    action: "update",
    possession: "any",
  })
  async connectApplications(
    @common.Param() params: JobPostWhereUniqueInput,
    @common.Body() body: ApplicationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      applications: {
        connect: body,
      },
    };
    await this.service.updateJobPost({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/applications")
  @nestAccessControl.UseRoles({
    resource: "JobPost",
    action: "update",
    possession: "any",
  })
  async updateApplications(
    @common.Param() params: JobPostWhereUniqueInput,
    @common.Body() body: ApplicationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      applications: {
        set: body,
      },
    };
    await this.service.updateJobPost({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/applications")
  @nestAccessControl.UseRoles({
    resource: "JobPost",
    action: "update",
    possession: "any",
  })
  async disconnectApplications(
    @common.Param() params: JobPostWhereUniqueInput,
    @common.Body() body: ApplicationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      applications: {
        disconnect: body,
      },
    };
    await this.service.updateJobPost({
      where: params,
      data,
      select: { id: true },
    });
  }
}
